server:
  port: 8006
spring:
  application:
    name: gulimall-thirdpart
  cloud:
    nacos:
      discovery:
        server-addr: fftf.fun:8848
    alicloud:
      access-key:  
      secret-key:  
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: qc-upload-file
logging:
  level:
    root: debug
