server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: fftf.fun:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        #路由断言规则数组
        #id作为唯一标识
        - id: test_baidu
          uri: https://www.baidu.com
          #断言里的参数里有uri=baidu跳转到uri
          predicates:
            - Query=uri,baidu

        - id: test_qq
          uri: https://www.qq.com
          predicates:
            - Query=uri,qq
        ####路由配置规则  精确的路由放在最前面 模糊的路由放在后面
        ##配置前端请求路由到product
        - id: product_route
          ##lb nacos的负载均衡的写法
          uri: lb://gulimall-product
          predicates:
          - Path=/api/product/**
          filters:
          - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        ##配置前端请求路由到product
        - id: thirdpart_route
          ##lb nacos的负载均衡的写法
          uri: lb://gulimall-thirdpart
          predicates:
          - Path=/api/thirdpart/**
          filters:
          - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        ##配置前端请求路由到renren
        - id: admin_route
          ##lb nacos的负载均衡的写法
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}


